
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Alignment alignment2;

	private global::Gtk.Button buttonExit;

	private global::Gtk.ScrolledWindow scrolledwindow;

	private global::Gtk.EventBox eventbox1;

	private global::Gtk.VBox vboxMedia;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Decorated = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment(1F, 0.5F, 0F, 1F);
		this.alignment2.Name = "alignment2";
		// Container child alignment2.Gtk.Container+ContainerChild
		this.buttonExit = new global::Gtk.Button();
		this.buttonExit.CanFocus = true;
		this.buttonExit.Name = "buttonExit";
		this.buttonExit.UseUnderline = true;
		this.buttonExit.Xalign = 1F;
		global::Gtk.Image w1 = new global::Gtk.Image();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Menu);
		this.buttonExit.Image = w1;
		this.alignment2.Add(this.buttonExit);
		this.vbox1.Add(this.alignment2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow = new global::Gtk.ScrolledWindow();
		this.scrolledwindow.Name = "scrolledwindow";
		this.scrolledwindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.scrolledwindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w4 = new global::Gtk.Viewport();
		w4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.eventbox1 = new global::Gtk.EventBox();
		this.eventbox1.Name = "eventbox1";
		// Container child eventbox1.Gtk.Container+ContainerChild
		this.vboxMedia = new global::Gtk.VBox();
		this.vboxMedia.Name = "vboxMedia";
		this.vboxMedia.Spacing = 6;
		this.eventbox1.Add(this.vboxMedia);
		w4.Add(this.eventbox1);
		this.scrolledwindow.Add(w4);
		this.vbox1.Add(this.scrolledwindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
	}
}
